services:
  redis:
    image: valkey/valkey:alpine
    volumes:
      - valkey-data:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/valkey &&
        echo "bind 0.0.0.0" > /usr/local/etc/valkey/valkey.conf &&
        echo "appendonly yes" >> /usr/local/etc/valkey/valkey.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/valkey/valkey.conf &&
        echo "databases 1" >> /usr/local/etc/valkey/valkey.conf &&
        # Periodic persistence
        echo "save 300 10" >> /usr/local/etc/valkey/valkey.conf &&
        # Resource management
        echo "maxmemory 1gb" >> /usr/local/etc/valkey/valkey.conf &&
        echo "maxmemory-policy allkeys-lru" >> /usr/local/etc/valkey/valkey.conf &&
        echo "maxclients 10000" >> /usr/local/etc/valkey/valkey.conf &&
        echo "tcp-backlog 511" >> /usr/local/etc/valkey/valkey.conf &&
        echo "lazyfree-lazy-server-del yes" >> /usr/local/etc/valkey/valkey.conf &&
        # Configure access
        echo "user default on nopass ~* +@all" > /usr/local/etc/valkey/users.acl &&
        # Start service
        valkey-server /usr/local/etc/valkey/valkey.conf --aclfile /usr/local/etc/valkey/users.acl
      '
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    ulimits:
      # Increase file descriptor limit
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: "511"
      # vm.overcommit_memory: "1" doesn't work here
    tty: true
    stdin_open: true

volumes:
  valkey-data: